---
server.http2.enabled: true
spring:
  main.banner-mode: "off"
  profiles:
    active: local

  datasource:
    driver-class-name: org.postgresql.Driver

  flyway.enabled: true

logging:
  level:
    org.springframework.web.servlet: INFO
    Exposed: DEBUG



app:
  appName: "kotlin-playground"
---
